<a href="https://colab.research.google.com/github/debabratahazra/scaler_code/blob/master/User_Movie_Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import Libraries
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings('ignore')
print("pandas version ",pd.__version__)

pandas version  2.2.2

In [ ]:
!wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1Q9UJtrN_v_dS-garl5gQ1I_SotGhye_1' -O "movies.csv"
!wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1HOFWUAMFlYbd-gk1B2IyV2-hXDZI7gKR' -O "ratings.csv"
!wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1b7_yRRBs3s3atp1WQHN2GU577vxY8u_h' -O "users.csv"

--2025-07-21 16:02:53--  https://drive.google.com/uc?export=download&id=1Q9UJtrN_v_dS-garl5gQ1I_SotGhye_1
Resolving drive.google.com (drive.google.com)... 172.217.0.78, 2607:f8b0:4025:810::200e
Connecting to drive.google.com (drive.google.com)|172.217.0.78|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1Q9UJtrN_v_dS-garl5gQ1I_SotGhye_1&export=download [following]
--2025-07-21 16:02:53--  https://drive.usercontent.google.com/download?id=1Q9UJtrN_v_dS-garl5gQ1I_SotGhye_1&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 172.217.7.33, 2607:f8b0:4025:804::2001
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|172.217.7.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 515699 (504K) [application/octet-stream]
Saving to: ‘movies.csv’

movies.csv          100%[===================>] 503.61K  --.-KB/s    in 0.08s

2025-07-21 16:02:55 (6.55 MB/s) - ‘movies.csv’ saved [515699/515699]

--2025-07-21 16:02:55--  https://drive.google.com/uc?export=download&id=1HOFWUAMFlYbd-gk1B2IyV2-hXDZI7gKR
Resolving drive.google.com (drive.google.com)... 172.217.0.78, 2607:f8b0:4025:810::200e
Connecting to drive.google.com (drive.google.com)|172.217.0.78|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1HOFWUAMFlYbd-gk1B2IyV2-hXDZI7gKR&export=download [following]
--2025-07-21 16:02:55--  https://drive.usercontent.google.com/download?id=1HOFWUAMFlYbd-gk1B2IyV2-hXDZI7gKR&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 172.217.7.33, 2607:f8b0:4025:804::2001
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|172.217.7.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2475052 (2.4M) [application/octet-stream]
Saving to: ‘ratings.csv’

ratings.csv         100%[===================>]   2.36M  --.-KB/s    in 0.08s

2025-07-21 16:02:58 (28.0 MB/s) - ‘ratings.csv’ saved [2475052/2475052]

--2025-07-21 16:02:58--  https://drive.google.com/uc?export=download&id=1b7_yRRBs3s3atp1WQHN2GU577vxY8u_h
Resolving drive.google.com (drive.google.com)... 172.217.0.78, 2607:f8b0:4025:810::200e
Connecting to drive.google.com (drive.google.com)|172.217.0.78|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1b7_yRRBs3s3atp1WQHN2GU577vxY8u_h&export=download [following]
--2025-07-21 16:02:58--  https://drive.usercontent.google.com/download?id=1b7_yRRBs3s3atp1WQHN2GU577vxY8u_h&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 172.217.7.33, 2607:f8b0:4025:804::2001
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|172.217.7.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16784 (16K) [application/octet-stream]
Saving to: ‘users.csv’

users.csv           100%[===================>]  16.39K  --.-KB/s    in 0s

2025-07-21 16:02:59 (99.9 MB/s) - ‘users.csv’ saved [16784/16784]

In [ ]:
# Loading Data
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

In [ ]:
select_movies = ratings.movieId.value_counts().head(1000).index.to_list()
movies = movies.loc[movies.movieId.isin(select_movies)]
ratings = ratings.loc[ratings.movieId.isin(select_movies)]

In [ ]:
select_movies = ratings.movieId.value_counts().head(1000).index.to_list()
movies = movies.loc[movies.movieId.isin(select_movies)]
ratings = ratings.loc[ratings.movieId.isin(select_movies)]

In [ ]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
...,...,...,...
9908,109374,"Grand Budapest Hotel, The (2014)",Comedy|Drama
9914,109487,Interstellar (2014),Sci-Fi|IMAX
9975,111759,Edge of Tomorrow (2014),Action|Sci-Fi|IMAX
10005,112852,Guardians of the Galaxy (2014),Action|Adventure|Sci-Fi
10089,116797,The Imitation Game (2014),Drama|Thriller|War

In [ ]:
ratings

        userId  movieId  rating   timestamp
0            1       16     4.0  1217897793
1            1       24     1.5  1217895807
2            1       32     4.0  1217896246
3            1       47     4.0  1217896556
4            1       50     4.0  1217896523
...        ...      ...     ...         ...
105148     668   109374     4.0  1415763807
105151     668   109487     4.0  1415421771
105185     668   111759     3.0  1413728719
105205     668   112852     4.0  1433992065
105252     668   116797     4.0  1422970740

[63250 rows x 4 columns]

In [ ]:
m = movies.copy()
m['genres'] = m['genres'].str.split('|')
m = m.explode('genres')

m

       movieId                           title     genres
0            1                Toy Story (1995)  Adventure
0            1                Toy Story (1995)  Animation
0            1                Toy Story (1995)   Children
0            1                Toy Story (1995)     Comedy
0            1                Toy Story (1995)    Fantasy
...        ...                             ...        ...
10005   112852  Guardians of the Galaxy (2014)  Adventure
10005   112852  Guardians of the Galaxy (2014)     Sci-Fi
10089   116797       The Imitation Game (2014)      Drama
10089   116797       The Imitation Game (2014)   Thriller
10089   116797       The Imitation Game (2014)        War

[2792 rows x 3 columns]

In [ ]:
m = m.pivot(index='movieId', columns='genres', values='title')
m

genres,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,
1,NaN,Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),NaN,NaN,NaN,Toy Story (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Jumanji (1995),NaN,Jumanji (1995),NaN,NaN,NaN,NaN,Jumanji (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,Grumpier Old Men (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Grumpier Old Men (1995),NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,Father of the Bride Part II (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Heat (1995),NaN,NaN,NaN,NaN,Heat (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Heat (1995),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109374,NaN,NaN,NaN,NaN,"Grand Budapest Hotel, The (2014)",NaN,NaN,"Grand Budapest Hotel, The (2014)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Interstellar (2014),NaN,NaN,NaN,Interstellar (2014),NaN,NaN,NaN
111759,Edge of Tomorrow (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Edge of Tomorrow (2014),NaN,NaN,NaN,Edge of Tomorrow (2014),NaN,NaN,NaN
112852,Guardians of the Galaxy (2014),Guardians of the Galaxy (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guardians of the Galaxy (2014),NaN,NaN,NaN
116797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The Imitation Game (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The Imitation Game (2014),The Imitation Game (2014),NaN

In [ ]:
m = movies.copy()
m['genres'] = m['genres'].str.split('|')
m = m.explode('genres')
m = m.pivot(index='movieId', columns='genres', values='title')
m = ~m.isna()
m = m.astype(int)
m.head(2)

genres,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,
1,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [ ]:
r = ratings.copy()

In [ ]:
r['hour'] = r['timestamp'].apply(lambda x: datetime.fromtimestamp(x).hour)
r.tail()

        userId  movieId  rating   timestamp  hour
105148     668   109374     4.0  1415763807     3
105151     668   109487     4.0  1415421771     4
105185     668   111759     3.0  1413728719    14
105205     668   112852     4.0  1433992065     3
105252     668   116797     4.0  1422970740    13

In [ ]:
users = pd.read_csv('users.csv')
users = users.merge(r.groupby('userId').rating.mean().reset_index(), on='userId')
users = users.merge(r.groupby('userId').hour.mean().reset_index(), on='userId')
users.head(2)

   userId  age  time_spent_per_day    rating  hour
0       1   16            3.976315  3.691589   0.0
1       2   24            1.891303  3.923077  16.0

In [ ]:
u = users.copy()
u = u.set_index('userId')
u.columns = ['age', 'time_spent_per_day', 'u_avg_rating', 'hour']

scaler = StandardScaler()
u = pd.DataFrame(scaler.fit_transform(u), columns=u.columns, index=u.index)
u.head(2)

             age  time_spent_per_day  u_avg_rating      hour
userId
1      -1.470292            0.341073     -0.071853 -1.900589
2      -0.135616           -1.079947      0.428590  0.610169

In [ ]:
m.head()

genres,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,
1,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
5,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0

In [ ]:
u.head()

             age  time_spent_per_day  u_avg_rating      hour
userId
1      -1.470292            0.341073     -0.071853 -1.900589
2      -0.135616           -1.079947      0.428590  0.610169
3      -0.802954            0.712624      0.176463 -0.488288
4      -0.302450           -0.940926      0.912806 -1.577514
5       1.699565           -1.169532     -1.859109  1.080936

In [ ]:
ratings

        userId  movieId  rating   timestamp
0            1       16     4.0  1217897793
1            1       24     1.5  1217895807
2            1       32     4.0  1217896246
3            1       47     4.0  1217896556
4            1       50     4.0  1217896523
...        ...      ...     ...         ...
105148     668   109374     4.0  1415763807
105151     668   109487     4.0  1415421771
105185     668   111759     3.0  1413728719
105205     668   112852     4.0  1433992065
105252     668   116797     4.0  1422970740

[63250 rows x 4 columns]

In [ ]:
X = ratings[['movieId', 'userId', 'rating']].copy()
X = X.merge(u.reset_index(), on='userId', how='right')
X = X.merge(m.reset_index(), on='movieId', how='right')
X

,movieId,userId,rating,age,time_spent_per_day,u_avg_rating,hour,Action,Adventure,Animation,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,2,5.0,-0.135616,-1.079947,0.428590,0.610169,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,5,4.0,1.699565,-1.169532,-1.859109,1.080936,0,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,8,5.0,0.364888,0.298545,0.162516,0.453247,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,11,4.0,-1.303458,0.513712,-0.379135,-0.424484,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4,1,14,4.0,-0.302450,1.251552,-0.377947,-0.488288,0,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63245,116797,606,4.0,-0.302450,1.470639,0.128123,0.581638,0,0,0,...,0,0,0,0,0,0,0,1,1,0
63246,116797,619,4.0,0.364888,1.140836,-0.395963,-0.017520,0,0,0,...,0,0,0,0,0,0,0,1,1,0
63247,116797,622,4.0,-0.636119,-0.301899,0.376805,-0.189584,0,0,0,...,0,0,0,0,0,0,0,1,1,0
63248,116797,642,4.0,-0.802954,-0.783329,0.722054,-1.452899,0,0,0,...,0,0,0,0,0,0,0,1,1,0
63249,116797,668,4.0,-0.135616,-0.516031,-1.487486,-0.371838,0,0,0,...,0,0,0,0,0,0,0,1,1,0

In [ ]:
X = X.drop(columns = ['movieId', 'userId'])
y = X.pop('rating')

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error as mse
mse(y_test, y_pred)**0.5

0.9037296217401495

In [ ]:
ratings.loc[ratings.userId==1].head()

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [ ]:
model.predict(pd.concat([u.loc[1],m.loc[1]]).values.reshape(1,-1))

array([3.65872312])

In [ ]:
ratings.head()

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [ ]:
rm = ratings.pivot(index = 'userId', columns ='movieId', values = 'rating').fillna(0)
rm.head()

movieId,1,2,3,5,6,7,10,11,16,17,...,88125,89745,91529,96610,99114,109374,109487,111759,112852,116797
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5.0,0.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,3.0,0.0,3.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
(rm > 0).sum().sum() / (rm.shape[0] * rm.shape[1])

np.float64(0.09468562874251497)

In [ ]:
rm_small = rm.copy()
rm_small = rm_small[rm_small.columns[:100]]
rm_small = rm_small.head(100)

In [ ]:
rm_small.shape

(100, 100)

In [ ]:
K = 2
P = np.random.normal(size=(rm_small.shape[0], K))
Q = np.random.normal(size=(rm_small.shape[1], K))

def matrix_factorization(R, P, Q, K, steps=10000, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] == 0:
                    continue
                eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                x = P[i,:]
                P[i,:] += alpha * (2 * eij * Q[:,j]) # - beta * P[i][k])
                Q[:,j] += alpha * (2 * eij * x) # - beta * Q[k][j])
    return P, Q.T


P_, Q_ =  matrix_factorization(rm_small.values.copy(), P.copy(), Q.copy(), 0.2)

In [ ]:
# Predicted Values vs Actual Ratings
print(np.dot(P_[4], Q_[36]), rm_small.values[4, 36])
print(np.dot(P_[1], Q_[0]), rm_small.values[1, 0])
print(np.dot(P_[1], Q_[2]), rm_small.values[1, 2])
print(np.dot(P_[3], Q_[17]), rm_small.values[3, 17])

2.1395879093540495 0.0
3.972243395352925 5.0
3.074087295920273 2.0
4.011483266939342 5.0

In [ ]:
from sklearn.metrics import mean_squared_error as mse
rm_ = np.dot(P_, Q_.T)
mse(rm_small.values[rm_small > 0], rm_[rm_small > 0])**0.5

0.6468445362091065

In [ ]:
!pip install cmfrec

Collecting cmfrec
  Using cached cmfrec-3.5.1.post13.tar.gz (268 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cython in /usr/local/lib/python3.11/dist-packages (from cmfrec) (3.0.12)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.11/dist-packages (from cmfrec) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from cmfrec) (1.15.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from cmfrec) (2.2.2)
Collecting findblas (from cmfrec)
  Using cached findblas-0.1.26.post1-py3-none-any.whl
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->cmfrec) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->cmfrec) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->cmfrec) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->cmfrec) (1.17.0)
Building wheels for collected packages: cmfrec
  Building wheel for cmfrec (pyproject.toml) ... done
  Created wheel for cmfrec: filename=cmfrec-3.5.1.post13-cp311-cp311-linux_x86_64.whl size=5751666 sha256=95783fe77d242cdf663f4ed5921b98c832e919319cde3f5ba079e91e534b90a6
  Stored in directory: /root/.cache/pip/wheels/16/70/88/1f79fa4894c838ed64d0ab7833a5c7166610f8bfdf79f70c70
Successfully built cmfrec
Installing collected packages: findblas, cmfrec
Successfully installed cmfrec-3.5.1.post13 findblas-0.1.26.post1

In [ ]:
rm_raw = ratings[['userId', 'movieId', 'rating']].copy()
rm_raw.columns = ['UserId', 'ItemId', 'Rating']  # Lib requires specific column names
rm_raw.head(2)

   UserId  ItemId  Rating
0       1      16     4.0
1       1      24     1.5

In [ ]:
from cmfrec import CMF

model = CMF(method="als", k=2, lambda_=0.1, user_bias=False, item_bias=False, verbose=False)
model.fit(rm_raw)

Collective matrix factorization model
(explicit-feedback variant)

In [ ]:
model.A_.shape, model.B_.shape

((668, 2), (1000, 2))

In [ ]:
rm_raw.Rating.mean(), model.glob_mean_

(np.float64(3.6643557312252963), 3.664355754852295)

In [ ]:
from sklearn.metrics import mean_squared_error as mse

rm__ = np.dot(model.A_, model.B_.T) + model.glob_mean_
mse(rm.values[rm > 0], rm__[rm > 0])**0.5

1.0699028419688583