<a href="https://colab.research.google.com/github/debabratahazra/scaler_code/blob/master/User_Movie_Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Libraries
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings('ignore')
print("pandas version ",pd.__version__)

pandas version  2.3.0

In [2]:
# !wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1Q9UJtrN_v_dS-garl5gQ1I_SotGhye_1' -O "movies.csv"
# !wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1HOFWUAMFlYbd-gk1B2IyV2-hXDZI7gKR' -O "ratings.csv"
# !wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1b7_yRRBs3s3atp1WQHN2GU577vxY8u_h' -O "users.csv"

'wget' is not recognized as an internal or external command,
operable program or batch file.
'id' is not recognized as an internal or external command,
operable program or batch file.
'wget' is not recognized as an internal or external command,
operable program or batch file.
'id' is not recognized as an internal or external command,
operable program or batch file.
'wget' is not recognized as an internal or external command,
operable program or batch file.
'id' is not recognized as an internal or external command,
operable program or batch file.

In [3]:
!curl -L -o "movies.csv" "https://drive.google.com/uc?export=download&id=1Q9UJtrN_v_dS-garl5gQ1I_SotGhye_1"
!curl -L -o "ratings.csv" "https://drive.google.com/uc?export=download&id=1HOFWUAMFlYbd-gk1B2IyV2-hXDZI7gKR"
!curl -L -o "users.csv" "https://drive.google.com/uc?export=download&id=1b7_yRRBs3s3atp1WQHN2GU577vxY8u_h"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100  503k  100  503k    0     0   176k      0  0:00:02  0:00:02 --:--:--  523k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100 2417k  100 2417k    0     0   766k      0  0:00:03  0:00:03 --:--:-- 1404k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100 16784  100 16784    0     0   6722      0  0:00:02  0:00:02 --:--:-- 16122

In [4]:
# Loading Data
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

In [5]:
select_movies = ratings.movieId.value_counts().head(1000).index.to_list()
movies = movies.loc[movies.movieId.isin(select_movies)]
ratings = ratings.loc[ratings.movieId.isin(select_movies)]

In [6]:
select_movies = ratings.movieId.value_counts().head(1000).index.to_list()
movies = movies.loc[movies.movieId.isin(select_movies)]
ratings = ratings.loc[ratings.movieId.isin(select_movies)]

In [7]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
...,...,...,...
9908,109374,"Grand Budapest Hotel, The (2014)",Comedy|Drama
9914,109487,Interstellar (2014),Sci-Fi|IMAX
9975,111759,Edge of Tomorrow (2014),Action|Sci-Fi|IMAX
10005,112852,Guardians of the Galaxy (2014),Action|Adventure|Sci-Fi
10089,116797,The Imitation Game (2014),Drama|Thriller|War

In [8]:
ratings

        userId  movieId  rating   timestamp
0            1       16     4.0  1217897793
1            1       24     1.5  1217895807
2            1       32     4.0  1217896246
3            1       47     4.0  1217896556
4            1       50     4.0  1217896523
...        ...      ...     ...         ...
105148     668   109374     4.0  1415763807
105151     668   109487     4.0  1415421771
105185     668   111759     3.0  1413728719
105205     668   112852     4.0  1433992065
105252     668   116797     4.0  1422970740

[63250 rows x 4 columns]

In [9]:
m = movies.copy()
m['genres'] = m['genres'].str.split('|')
m = m.explode('genres')

m

       movieId                           title     genres
0            1                Toy Story (1995)  Adventure
0            1                Toy Story (1995)  Animation
0            1                Toy Story (1995)   Children
0            1                Toy Story (1995)     Comedy
0            1                Toy Story (1995)    Fantasy
...        ...                             ...        ...
10005   112852  Guardians of the Galaxy (2014)  Adventure
10005   112852  Guardians of the Galaxy (2014)     Sci-Fi
10089   116797       The Imitation Game (2014)      Drama
10089   116797       The Imitation Game (2014)   Thriller
10089   116797       The Imitation Game (2014)        War

[2792 rows x 3 columns]

In [10]:
m = m.pivot(index='movieId', columns='genres', values='title')
m

genres,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,
1,NaN,Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),NaN,NaN,NaN,Toy Story (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Jumanji (1995),NaN,Jumanji (1995),NaN,NaN,NaN,NaN,Jumanji (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,Grumpier Old Men (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Grumpier Old Men (1995),NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,Father of the Bride Part II (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Heat (1995),NaN,NaN,NaN,NaN,Heat (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Heat (1995),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109374,NaN,NaN,NaN,NaN,"Grand Budapest Hotel, The (2014)",NaN,NaN,"Grand Budapest Hotel, The (2014)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Interstellar (2014),NaN,NaN,NaN,Interstellar (2014),NaN,NaN,NaN
111759,Edge of Tomorrow (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Edge of Tomorrow (2014),NaN,NaN,NaN,Edge of Tomorrow (2014),NaN,NaN,NaN
112852,Guardians of the Galaxy (2014),Guardians of the Galaxy (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guardians of the Galaxy (2014),NaN,NaN,NaN
116797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The Imitation Game (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The Imitation Game (2014),The Imitation Game (2014),NaN

In [11]:
m = movies.copy()
m['genres'] = m['genres'].str.split('|')
m = m.explode('genres')
m = m.pivot(index='movieId', columns='genres', values='title')
m = ~m.isna()
m = m.astype(int)
m.head(2)

genres,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,
1,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [12]:
r = ratings.copy()

In [13]:
r['hour'] = r['timestamp'].apply(lambda x: datetime.fromtimestamp(x).hour)
r.tail()

        userId  movieId  rating   timestamp  hour
105148     668   109374     4.0  1415763807     9
105151     668   109487     4.0  1415421771    10
105185     668   111759     3.0  1413728719    19
105205     668   112852     4.0  1433992065     8
105252     668   116797     4.0  1422970740    19

In [14]:
users = pd.read_csv('users.csv')
users = users.merge(r.groupby('userId').rating.mean().reset_index(), on='userId')
users = users.merge(r.groupby('userId').hour.mean().reset_index(), on='userId')
users.head(2)

   userId  age  time_spent_per_day    rating       hour
0       1   16            3.976315  3.691589   5.616822
1       2   24            1.891303  3.923077  21.000000

In [15]:
u = users.copy()
u = u.set_index('userId')
u.columns = ['age', 'time_spent_per_day', 'u_avg_rating', 'hour']

scaler = StandardScaler()
u = pd.DataFrame(scaler.fit_transform(u), columns=u.columns, index=u.index)
u.head(2)

             age  time_spent_per_day  u_avg_rating      hour
userId
1      -1.470292            0.341073     -0.071853 -0.881444
2      -0.135616           -1.079947      0.428590  1.478047

In [16]:
m.head()

genres,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,
1,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
5,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0

In [17]:
u.head()

             age  time_spent_per_day  u_avg_rating      hour
userId
1      -1.470292            0.341073     -0.071853 -0.881444
2      -0.135616           -1.079947      0.428590  1.478047
3      -0.802954            0.712624      0.176463  0.461278
4      -0.302450           -0.940926      0.912806 -0.515910
5       1.699565           -1.169532     -1.859109 -1.664197

In [18]:
ratings

        userId  movieId  rating   timestamp
0            1       16     4.0  1217897793
1            1       24     1.5  1217895807
2            1       32     4.0  1217896246
3            1       47     4.0  1217896556
4            1       50     4.0  1217896523
...        ...      ...     ...         ...
105148     668   109374     4.0  1415763807
105151     668   109487     4.0  1415421771
105185     668   111759     3.0  1413728719
105205     668   112852     4.0  1433992065
105252     668   116797     4.0  1422970740

[63250 rows x 4 columns]

In [19]:
X = ratings[['movieId', 'userId', 'rating']].copy()
X = X.merge(u.reset_index(), on='userId', how='right')
X = X.merge(m.reset_index(), on='movieId', how='right')
X

,movieId,userId,rating,age,time_spent_per_day,u_avg_rating,hour,Action,Adventure,Animation,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,2,5.0,-0.135616,-1.079947,0.428590,1.478047,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,5,4.0,1.699565,-1.169532,-1.859109,-1.664197,0,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,8,5.0,0.364888,0.298545,0.162516,1.324666,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,11,4.0,-1.303458,0.513712,-0.379135,0.557760,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4,1,14,4.0,-0.302450,1.251552,-0.377947,0.557760,0,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63245,116797,606,4.0,-0.302450,1.470639,0.128123,1.491991,0,0,0,...,0,0,0,0,0,0,0,1,1,0
63246,116797,619,4.0,0.364888,1.140836,-0.395963,0.898607,0,0,0,...,0,0,0,0,0,0,0,1,1,0
63247,116797,622,4.0,-0.636119,-0.301899,0.376805,-0.176856,0,0,0,...,0,0,0,0,0,0,0,1,1,0
63248,116797,642,4.0,-0.802954,-0.783329,0.722054,-0.488842,0,0,0,...,0,0,0,0,0,0,0,1,1,0
63249,116797,668,4.0,-0.135616,-0.516031,-1.487486,0.097442,0,0,0,...,0,0,0,0,0,0,0,1,1,0

In [20]:
X = X.drop(columns = ['movieId', 'userId'])
y = X.pop('rating')

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [22]:
from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [23]:
from sklearn.metrics import mean_squared_error as mse
mse(y_test, y_pred)**0.5

0.9034904525772898

In [24]:
ratings.loc[ratings.userId==1].head()

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [25]:
model.predict(pd.concat([u.loc[1],m.loc[1]]).values.reshape(1,-1))

array([3.69051689])

In [26]:
ratings.head()

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [27]:
rm = ratings.pivot(index = 'userId', columns ='movieId', values = 'rating').fillna(0)
rm.head()

movieId,1,2,3,5,6,7,10,11,16,17,...,88125,89745,91529,96610,99114,109374,109487,111759,112852,116797
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5.0,0.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,3.0,0.0,3.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
(rm > 0).sum().sum() / (rm.shape[0] * rm.shape[1])

np.float64(0.09468562874251497)

In [29]:
rm_small = rm.copy()
rm_small = rm_small[rm_small.columns[:100]]
rm_small = rm_small.head(100)

In [30]:
rm_small.shape

(100, 100)

In [31]:
K = 2
P = np.random.normal(size=(rm_small.shape[0], K))
Q = np.random.normal(size=(rm_small.shape[1], K))

def matrix_factorization(R, P, Q, K, steps=10000, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] == 0:
                    continue
                eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                x = P[i,:]
                P[i,:] += alpha * (2 * eij * Q[:,j]) # - beta * P[i][k])
                Q[:,j] += alpha * (2 * eij * x) # - beta * Q[k][j])
    return P, Q.T


P_, Q_ =  matrix_factorization(rm_small.values.copy(), P.copy(), Q.copy(), 0.2)

In [32]:
# Predicted Values vs Actual Ratings
print(np.dot(P_[4], Q_[36]), rm_small.values[4, 36])
print(np.dot(P_[1], Q_[0]), rm_small.values[1, 0])
print(np.dot(P_[1], Q_[2]), rm_small.values[1, 2])
print(np.dot(P_[3], Q_[17]), rm_small.values[3, 17])

1.599112916858916 0.0
4.065871782408598 5.0
3.2114809781543316 2.0
5.065038105063676 5.0

In [33]:
from sklearn.metrics import mean_squared_error as mse
rm_ = np.dot(P_, Q_.T)
mse(rm_small.values[rm_small > 0], rm_[rm_small > 0])**0.5

0.6778715787557917

In [2]:
!pip install cmfrec

Defaulting to user installation because normal site-packages is not writeable
Collecting cmfrec
  Using cached cmfrec-3.5.1.post13.tar.gz (268 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting cython (from cmfrec)
  Using cached cython-3.1.2-cp312-cp312-win_amd64.whl.metadata (6.0 kB)
Requirement already satisfied: numpy>=1.25 in c:\users\hazra\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from cmfrec) (2.0.2)
Requirement already satisfied: scipy in c:\users\hazra\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from cmfrec) (1.15.3)
Requirement already satisfied: pandas in c:\users\hazra\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from cmfrec) (2.3.0)
Collecting findblas (from cmfrec)
  Using cached findblas-0.1.26.post1-py3-none-any.whl
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hazra\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->cmfrec) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hazra\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->cmfrec) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hazra\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas->cmfrec) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hazra\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas->cmfrec) (1.17.0)
Using cached cython-3.1.2-cp312-cp312-win_amd64.whl (2.7 MB)
Building wheels for collected packages: cmfrec
  Building wheel for cmfrec (pyproject.toml): started
  Building wheel for cmfrec (pyproject.toml): finished with status 'done'
  Created wheel for cmfrec: filename=cmfrec-3.5.1.post13-cp312-cp312-win_amd64.whl size=960915 sha256=b87322eb6b2dd16408251b249d9be21918495e2aa986d64cd98b8868a87af243
  Stored in directory: c:\users\hazra\appdata\local\pip\cache\wheels\46\9d\a7\03614a1633b40dde9aeb6eb12265f9c684feba1e3d82fe05bf
Successfully built cmfrec
Installing collected packages: findblas, cython, cmfrec

   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   ------------- -------------------------- 1/3 [cython]
   -------------------------- ------------- 2/3 [cmfrec]
   ---------------------------------------- 3/3 [cmfrec]

Successfully installed cmfrec-3.5.1.post13 cython-3.1.2 findblas-0.1.26.post1

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Hazra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Hazra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Hazra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages)

In [35]:
rm_raw = ratings[['userId', 'movieId', 'rating']].copy()
rm_raw.columns = ['UserId', 'ItemId', 'Rating']  # Lib requires specific column names
rm_raw.head(2)

   UserId  ItemId  Rating
0       1      16     4.0
1       1      24     1.5

In [38]:
from cmfrec import CMF

model = CMF(method="als", k=2, lambda_=0.1, user_bias=False, item_bias=False, verbose=False)
model.fit(rm_raw)

ModuleNotFoundError: No module named 'cmfrec'

In [ ]:
model.A_.shape, model.B_.shape

((668, 2), (1000, 2))

In [ ]:
rm_raw.Rating.mean(), model.glob_mean_

(np.float64(3.6643557312252963), 3.664355754852295)

In [ ]:
from sklearn.metrics import mean_squared_error as mse

rm__ = np.dot(model.A_, model.B_.T) + model.glob_mean_
mse(rm.values[rm > 0], rm__[rm > 0])**0.5

1.0699028419688583